 [
  {
    sMenuID: "DASH-0",
    sGlobalID: "DASH-0",
    sMenuName: "Dashboard",
    sMenuLocation: "DRAWER",
    sMenuContainer: "MENU",
    sImageType: "SpeedOutlined",
    sImagePath: "",
    sImageProps: "{ \"fontSize\" : \"small\"}",
    sMenuProps: "",
    sGridProps: null,
    sMenuRoute: "/form/get/dashboard",
    sToolTip: "",
    bDisplayName: 1,
    iOrder: 1,
    submenus: []
  },
  {
    sMenuID: "INV-0",
    sGlobalID: "INV-0",
    sMenuName: "Inventory",
    sMenuLocation: "DRAWER",
    sMenuContainer: "MENU",
    sImageType: "Inventory2Outlined",
    sImagePath: null,
    sImageProps: "{ \"fontSize\" : \"small\"}",
    sMenuProps: null,
    sGridProps: null,
    sMenuRoute: "",
    sToolTip: "",
    bDisplayName: 1,
    iOrder: 2,
    submenus: [
      {
        sMenuID: "INV-2",
        sGlobalID: "INV-2",
        sParentID: "INV-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Inventory Items",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/inventoryMain",
        iOrder: 1,
        sToolTip: "",
        sDefaultActionImage: "",
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "",
        sDefaultActionMenuRoute: "",
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "INV-3",
        sGlobalID: "INV-3",
        sParentID: "INV-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Combined Items",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/comboItemsMain",
        iOrder: 2,
        sToolTip: "",
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "INV-7",
        sGlobalID: "INV-7",
        sParentID: "INV-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Inventory Kit",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/inventoryKitMain",
        iOrder: 3,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "INV-4",
        sGlobalID: "INV-4",
        sParentID: "INV-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Goods Received",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/goodsReceivedMain",
        iOrder: 4,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "INV-5",
        sGlobalID: "INV-5",
        sParentID: "INV-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Transfer Items",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/inventoryTransferMain",
        iOrder: 5,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "INV-6",
        sGlobalID: "INV-6",
        sParentID: "INV-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Adjust Inventory",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/inventoryAdjustMain",
        iOrder: 6,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      }
    ]
  },
  {
    sMenuID: "SAL-0",
    sGlobalID: "SAL-0",
    sMenuName: "Sales",
    sMenuLocation: "DRAWER",
    sMenuContainer: "MENU",
    sImageType: "MonetizationOnOutlined",
    sImagePath: null,
    sImageProps: "{ \"fontSize\" : \"small\"}",
    sMenuProps: null,
    sGridProps: null,
    sMenuRoute: "",
    sToolTip: "",
    bDisplayName: 1,
    iOrder: 3,
    submenus: [
      {
        sMenuID: "SAL-1",
        sGlobalID: "SAL-1",
        sParentID: "SAL-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Customers",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/customerMain",
        iOrder: 1,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "SAL-5",
        sGlobalID: "SAL-5",
        sParentID: "SAL-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Employees",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/employeeMain",
        iOrder: 2,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "SAL-7",
        sGlobalID: "SAL-7",
        sParentID: "SAL-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Price List",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/customerPriceListMain",
        iOrder: 3,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "SAL-2",
        sGlobalID: "SAL-2",
        sParentID: "SAL-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Sales Order",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/soMain",
        iOrder: 5,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "SAL-3",
        sGlobalID: "SAL-3",
        sParentID: "SAL-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "For Packing",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/packingMain",
        iOrder: 6,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "SAL-4",
        sGlobalID: "SAL-4",
        sParentID: "SAL-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "For Delivery",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/deliveryMain",
        iOrder: 7,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "SAL-10",
        sGlobalID: "SAL-10",
        sParentID: "SAL-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Receive Payment",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/paymentMain",
        iOrder: 8,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "SAL-6",
        sGlobalID: "SAL-6",
        sParentID: "SAL-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Sales Invoice",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/invoiceMain",
        iOrder: 9,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "SAL-8",
        sGlobalID: "SAL-8",
        sParentID: "SAL-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Sales Receipt",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/receiptMain",
        iOrder: 10,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "SAL-9",
        sGlobalID: "SAL-9",
        sParentID: "SAL-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Credit Note",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/creditNoteMain",
        iOrder: 11,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      }
    ]
  },
  {
    sMenuID: "PUR-0",
    sGlobalID: "PUR-0",
    sMenuName: "Purchases",
    sMenuLocation: "DRAWER",
    sMenuContainer: "MENU",
    sImageType: "ShoppingBagOutlined",
    sImagePath: null,
    sImageProps: "{ \"fontSize\" : \"small\"}",
    sMenuProps: null,
    sGridProps: null,
    sMenuRoute: null,
    sToolTip: "",
    bDisplayName: 1,
    iOrder: 4,
    submenus: [
      {
        sMenuID: "PUR-1",
        sGlobalID: "PUR-1",
        sParentID: "PUR-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Vendors",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/vendorMain",
        iOrder: 1,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "PUR-6",
        sGlobalID: "PUR-6",
        sParentID: "PUR-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Vendor Pricelist",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/vendorPriceListMain",
        iOrder: 2,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "PUR-2",
        sGlobalID: "PUR-2",
        sParentID: "PUR-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Purchase Orders",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/poMain",
        iOrder: 3,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "PUR-3",
        sGlobalID: "PUR-3",
        sParentID: "PUR-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Bills",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/purchaseInvoiceAdd",
        iOrder: 4,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "PUR-4",
        sGlobalID: "PUR-4",
        sParentID: "PUR-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Vendor Payment",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/billPaymentMain",
        iOrder: 5,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "PUR-5",
        sGlobalID: "PUR-5",
        sParentID: "PUR-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Debit Note",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/debitNoteMain",
        iOrder: 6,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: "{ \"fontSize\" : \"small\"}",
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      }
    ]
  },
  {
    sMenuID: "ACCOUNTING-0",
    sGlobalID: "ACCOUNTING-0",
    sMenuName: "Accounting",
    sMenuLocation: "DRAWER",
    sMenuContainer: "MENU",
    sImageType: "AccountBoxOutlinedIcon",
    sImagePath: null,
    sImageProps: "{ \"fontSize\" : \"small\"}",
    sMenuProps: null,
    sGridProps: null,
    sMenuRoute: null,
    sToolTip: "",
    bDisplayName: 1,
    iOrder: 5,
    submenus: [
      {
        sMenuID: "ACCOUNTING-0-1",
        sGlobalID: "ACCOUNTING-0-1",
        sParentID: "ACCOUNTING-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Chart of Accounts",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/coaMain",
        iOrder: 1,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "ACCOUNTING-0-2",
        sGlobalID: "ACCOUNTING-0-2",
        sParentID: "ACCOUNTING-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Cash-in",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: null,
        iOrder: 2,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "ACCOUNTING-0-3",
        sGlobalID: "ACCOUNTING-0-3",
        sParentID: "ACCOUNTING-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Cash Out",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: null,
        iOrder: 3,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "ACCOUNTING-0-4",
        sGlobalID: "ACCOUNTING-0-4",
        sParentID: "ACCOUNTING-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Journal Entry",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: null,
        iOrder: 4,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      }
    ]
  },
  {
    sMenuID: "REPORTS-0",
    sGlobalID: "REPORTS-0",
    sMenuName: "Reports",
    sMenuLocation: "DRAWER",
    sMenuContainer: "MENU",
    sImageType: "AssessmentOutlinedIcon",
    sImagePath: null,
    sImageProps: "{ \"fontSize\" : \"small\"}",
    sMenuProps: null,
    sGridProps: null,
    sMenuRoute: null,
    sToolTip: null,
    bDisplayName: 1,
    iOrder: 6,
    submenus: []
  },
  {
    sMenuID: "SET-0",
    sGlobalID: "SET-0",
    sMenuName: "Settings",
    sMenuLocation: "DRAWER",
    sMenuContainer: "MENU",
    sImageType: "SettingsOutlinedIcon",
    sImagePath: null,
    sImageProps: "{ \"fontSize\" : \"small\"}",
    sMenuProps: null,
    sGridProps: null,
    sMenuRoute: "/form/get/settingsMain",
    sToolTip: "",
    bDisplayName: 1,
    iOrder: 7,
    submenus: []
  },
  {
    sMenuID: "TEST-0",
    sGlobalID: "TEST-0",
    sMenuName: "Module Test",
    sMenuLocation: "DRAWER",
    sMenuContainer: "MENU",
    sImageType: null,
    sImagePath: null,
    sImageProps: null,
    sMenuProps: "{\"variant\": \"outlined\", \"size\": \"small\"}",
    sGridProps: "{}",
    sMenuRoute: null,
    sToolTip: null,
    bDisplayName: 1,
    iOrder: 20,
    submenus: [
      {
        sMenuID: "TEST-14",
        sGlobalID: "TEST-14",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "TYPOGRAPHY",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testTypography",
        iOrder: 1,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-1",
        sGlobalID: "TEST-1",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "TEXTFIELDS",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testTextField",
        iOrder: 2,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-11",
        sGlobalID: "TEST-10",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "AUTOCOMPLETE",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testAutocomplete",
        iOrder: 3,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-5",
        sGlobalID: "TEST-5",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Input Table Default",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testInputTableDefault",
        iOrder: 4,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-4",
        sGlobalID: "TEST-4",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Multiple Table Submit",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testMultipleTable",
        iOrder: 5,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-6",
        sGlobalID: "TEST-6",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Test Record Reload",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testEditReload",
        iOrder: 6,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-7",
        sGlobalID: "TEST-7",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Test Table Reload",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testEditReloadTable",
        iOrder: 7,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-8",
        sGlobalID: "TEST-8",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Test Variables-Formatting",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testVariablesFormatting",
        iOrder: 8,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-9",
        sGlobalID: "TEST-9",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Test Debit Credit Table",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testDebitCreditTable",
        iOrder: 9,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-10",
        sGlobalID: "TEST-10",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Test Dialog",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testDialog",
        iOrder: 10,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-2",
        sGlobalID: "TEST-2",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Input Table Freeform",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testInputTableFreeForm",
        iOrder: 11,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-12",
        sGlobalID: "TEST-10",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Test RadioGroup",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testRadioButtonGroup",
        iOrder: 12,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-3",
        sGlobalID: "TEST-3",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Test Submit ",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "",
        iOrder: 12,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: [
          {
            sMenuID: "TEST-3-1",
            sGlobalID: "TEST-3-1",
            sParentID: "TEST-3",
            sImageType: null,
            sImagePath: null,
            sImageProps: null,
            sCaption: "Test 2nd level menu",
            sMenuProps: null,
            sGridProps: null,
            sMenuRoute: "",
            iOrder: 1,
            sToolTip: null,
            sDefaultActionImage: null,
            sDefaultActionImagePath: null,
            sDefaultActionImageProps: null,
            sDefaultActionMenuRoute: null,
            blDisplaySubmenu: 1,
            submenus: [
              {
                sMenuID: "TEST-3-1-1",
                sGlobalID: "TEST-3-1-1",
                sParentID: "TEST-3-1",
                sImageType: null,
                sImagePath: null,
                sImageProps: null,
                sCaption: "Test 3rd level menu",
                sMenuProps: null,
                sGridProps: null,
                sMenuRoute: null,
                iOrder: 2,
                sToolTip: null,
                sDefaultActionImage: null,
                sDefaultActionImagePath: null,
                sDefaultActionImageProps: null,
                sDefaultActionMenuRoute: null,
                blDisplaySubmenu: 1,
                submenus: [
                  {
                    sMenuID: "TEST-3-1-1-1",
                    sGlobalID: "TEST-3-1-1-1",
                    sParentID: "TEST-3-1-1",
                    sImageType: null,
                    sImagePath: null,
                    sImageProps: null,
                    sCaption: "Test 4th level menu",
                    sMenuProps: null,
                    sGridProps: null,
                    sMenuRoute: null,
                    iOrder: 1,
                    sToolTip: null,
                    sDefaultActionImage: null,
                    sDefaultActionImagePath: null,
                    sDefaultActionImageProps: null,
                    sDefaultActionMenuRoute: null,
                    blDisplaySubmenu: 1,
                    submenus: [
                      {
                        sMenuID: "TEST-3-1-1-1-1",
                        sGlobalID: "TEST-3-1-1-1-1",
                        sParentID: "TEST-3-1-1-1",
                        sImageType: null,
                        sImagePath: null,
                        sImageProps: null,
                        sCaption: "Test 5th level menu",
                        sMenuProps: null,
                        sGridProps: null,
                        sMenuRoute: "/form/get/testSubmit",
                        iOrder: 1,
                        sToolTip: null,
                        sDefaultActionImage: null,
                        sDefaultActionImagePath: null,
                        sDefaultActionImageProps: null,
                        sDefaultActionMenuRoute: null,
                        blDisplaySubmenu: 1,
                        submenus: []
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        sMenuID: "TEST-13",
        sGlobalID: "TEST-13",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Test DataGrid",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testDataGrid",
        iOrder: 13,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-15",
        sGlobalID: "TEST-15",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Test Select",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testSelect",
        iOrder: 15,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      },
      {
        sMenuID: "TEST-16",
        sGlobalID: "TEST-16",
        sParentID: "TEST-0",
        sImageType: null,
        sImagePath: null,
        sImageProps: null,
        sCaption: "Test Global Variable",
        sMenuProps: null,
        sGridProps: null,
        sMenuRoute: "/form/get/testGlobalVariable",
        iOrder: 16,
        sToolTip: null,
        sDefaultActionImage: null,
        sDefaultActionImagePath: null,
        sDefaultActionImageProps: null,
        sDefaultActionMenuRoute: null,
        blDisplaySubmenu: 1,
        submenus: []
      }
    ]
  }
]